name: push_release_nuget

# on push on master
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@main
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v2.0.0
      
    - name: Publish VL Nuget
      uses: vvvv/PublishVLNuget@1.0.43
      with:
        csproj: src\VL.Audio.LTC.sln
        nuspec: deployment\VL.Audio.LTC.nuspec
        icon-src: https://raw.githubusercontent.com/vvvv/PublicContent/master/nugeticon.png
        icon-dst: ./deployment/icon.png
        nuget-key: ${{ secrets.NUGET_KEY }}